# Generated by Django 5.1.4 on 2024-12-18 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_cuenta_fecha_apertura_alter_cuenta_moneda'),
        ('transacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_transaccion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='cuentas.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='cuentas.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('transferencia', 'Transferencia')], max_length=15),
        ),
    ]
