# Generated by Django 5.1.4 on 2024-12-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='notificar_transacciones',
            field=models.BooleanField(default=False, help_text='Activar notificaciones para transacciones sospechosas'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='saldo_minimo',
            field=models.DecimalField(decimal_places=2, help_text='Saldo mínimo para recibir alertas', max_digits=10),
        ),
    ]
