# Generated by Django 5.1.4 on 2024-12-18 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(default='light', max_length=50)),
                ('fuente', models.CharField(default='default', max_length=50)),
                ('layout', models.CharField(default='default', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
