# Generated by Django 5.1.4 on 2024-12-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3, verbose_name='Moneda'),
        ),
    ]
