# Generated by Django 5.1.4 on 2024-12-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_remove_cuenta_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(default='USD', max_length=10, verbose_name='Moneda'),
        ),
    ]
