# Generated by Django 5.1.4 on 2024-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_cuenta_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_apertura',
            field=models.DateTimeField(verbose_name='Fecha de Apertura'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar Americano'), ('EUR', 'Euro'), ('PEN', 'Sol Peruano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
