# Generated by Django 5.1.4 on 2024-12-18 18:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], default='GASTO', max_length=10)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='monto',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='nombre',
            field=models.CharField(default='Presupuesto', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PresupuestoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_utilizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('alerta_porcentaje', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.categoria')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='presupuestos.presupuesto')),
            ],
            options={
                'verbose_name': 'Categoría de Presupuesto',
                'verbose_name_plural': 'Categorías de Presupuesto',
                'unique_together': {('presupuesto', 'categoria')},
            },
        ),
    ]
