# Generated by Django 5.1.4 on 2024-12-18 18:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informe',
            options={'ordering': ['-fecha_generacion'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.RemoveField(
            model_name='informe',
            name='gastos_totales',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='ingresos_totales',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='saldo_neto',
        ),
        migrations.AddField(
            model_name='informe',
            name='archivo_generado',
            field=models.FileField(blank=True, null=True, upload_to='informes/'),
        ),
        migrations.AddField(
            model_name='informe',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERANDO', 'Generando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='formato',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='informe',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='tipo',
            field=models.CharField(choices=[('PRESTAMOS', 'Informe de Préstamos'), ('TRANSACCIONES', 'Informe de Transacciones'), ('CUENTAS', 'Estado de Cuentas'), ('GENERAL', 'Informe General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InformeDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cantidad_registros', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='informes.informe')),
            ],
        ),
    ]
