# Generated by Django 5.1.4 on 2024-12-18 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={},
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='cuenta_asociada',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='numero_tarjeta',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='saldo_disponible',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='tipo_tarjeta',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='numero',
            field=models.CharField(default='0000000000000000', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='titular',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('bloqueada', 'Bloqueada')], default='activa', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
    ]
